name: Master to Leader check
on: pull_request
jobs:
  master-leader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Words Really Matter
        uses: jjasghar/words-really-matter@v1.0.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: changing master to leader and more
          title: Changing Master to Leader and more
          body: This is changed Master to Leader, and Slave to Follower
          branch: master-to-leader
